---
name: Release CV

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Just
        uses: extractions/setup-just@v2

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Setup Typst
        uses: typst-community/setup-typst@v3
        with:
          cache-dependency-path: requirements.typ

      - name: Build resumes
        shell: bash
        run: |
          just build
          # compiles into "build" directory
          just generate

      - name: Create tag
        id: tag
        shell: bash
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          tag=$(date +'%Y-%m-%d_%s')
          git tag -a "$tag" -m "Update $tag"
          git push --tags
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: build/*
